name: test
on: [push, pull_request]
jobs:
  FirstJob:
    runs-on: self-hosted
    environment: test
    name: "FirstJob"
    steps:
      - run: echo "Hello from VM one"; sleep 120
  #SecondJob:
  #  runs-on: self-hosted
  #  name: "SecondJob"
  #  steps:
  #    - run: echo "Hello from VM two"; sleep 120
